import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "@/app/components/layout/header/header";
import Footer from "@/app/components/layout/footer/footer";
import React from "react";
import {ReduxProvider} from "@/app/redux/provider";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased text-slate-500 dark:text-slate-400 bg-white dark:bg-slate-900`}>
        <ReduxProvider>
          <div className="flex flex-col min-h-screen">
              <Header />
              {children}
              <Footer />
          </div>
        </ReduxProvider>
      </body>
    </html>
  )
}
